all: main.cpp codegen.cpp scanner.cpp scanner.h prase.cpp state.cpp grammar.cpp grammar.h AST.h codegen.h
	g++ main.cpp codegen.cpp scanner.cpp scanner.h prase.cpp state.cpp grammar.cpp grammar.h AST.h codegen.h -o compiler

clean:
	rm -f compiler